-- AlterTable
ALTER TABLE "ParkingImages" ALTER COLUMN "imageUrl" SET NOT NULL,
ALTER COLUMN "imageUrl" SET DATA TYPE TEXT,
ALTER COLUMN "imageId" SET NOT NULL,
ALTER COLUMN "imageId" SET DATA TYPE TEXT;
